trigger:
- master

pool:
  name: WindowVm

variables:
  # Define your Azure Container Registry information
  containerRegistry: 'azuredb2acr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  imageName: 'biradarsandeepdockermysqlspringbootexample'
  tag: '$(Build.BuildId)'
  vmImageName: 'windows-latest'  # Specify the Windows VM image

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: 'buildAndPush'
        repository: '$(containerRegistry)/$(imageName)'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
